apiVersion: apps/v1
kind: Deployment
metadata:
  name: cu-deployment
  namespace: cu
  labels:
    app: cu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cu
  template:
    metadata:
      labels:
        app: cu-app
    spec:
      containers:
        - name: cu-app
          image: ghcr.io/noname2048/cu:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
