name: delete-old-lightsail-images

on:
  schedule:
    # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
    # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.
    # 이 크론은 평일 5시 (한국시간 16시)에 실행됩니다.
    - cron: '0 7 * * *'

env:
  SERVICE_NAME: cu-container-service-1

jobs:
  cron:
    runs-on: ubu

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Configure AWS credentials (lightsail)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LIGHTSAIL_PUSHER_ACCESS }}
          aws-secret-access-key: ${{ secrets.LIGHTSAIL_PUSHER_SECRET }}
          aws-region: ap-northeast-2
      -
        name: Delete old lightsail images
        run: |
          IMAGES=$(aws lightsail get-container-images --service-name $SERVICE_NAME --profile lightsail | jq -r '.containerImages[] | .image')
          IMAGES_TO_DELETE=$(echo IMAGES | tail -n + 4)
          for IMAGE in $IMAGES_TO_DELETE
          do
            aws lightsail delete-container-image --service-name $SERVICE_NAME --image $IMAGE --profile lightsail
          done
