name: CRON

on:
  schedule:
    # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
    # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.
    # 이 크론은 평일 5시 (한국시간 17시)에 실행됩니다.
    - cron: '0 8 * * *'

env:
  SERVICE_NAME: cu-container-service-1

jobs:
  lightsail-maintenance:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Configure AWS credentials (lightsail)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LIGHTSAIL_PUSHER_ACCESS }}
          aws-secret-access-key: ${{ secrets.LIGHTSAIL_PUSHER_SECRET }}
          aws-region: ap-northeast-2
      -
        name: Delete old lightsail images
        working-directory: ./bckend/scripts
        run: |
          sh ./delete-images.sh
          
